import 'package:flutter/material.dart';

final Map<String, TextStyle> sqlTheme = {
  'root': const TextStyle(
    backgroundColor: Colors.transparent,
    color: Color(0xff333333),
  ),
  'keyword': const TextStyle(color: Colors.blue, fontWeight: FontWeight.bold),
  'string': const TextStyle(color: Colors.green),
  'number': const TextStyle(color: Colors.orange),
  'comment': const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  'literal': const TextStyle(color: Colors.purple),
  'variable': const TextStyle(color: Colors.teal),
  'type': const TextStyle(color: Colors.indigo),
  'function': const TextStyle(color: Colors.brown),
};

final Map<String, TextStyle> sqlDarkTheme = {
  'root': const TextStyle(
    backgroundColor: Colors.transparent,
    color: Color(0xffd4d4d4),
  ),
  'keyword': const TextStyle(
    color: Color(0xff569cd6),
    fontWeight: FontWeight.bold,
  ),
  'string': const TextStyle(color: Color(0xffce9178)),
  'number': const TextStyle(color: Color(0xffb5cea8)),
  'comment': const TextStyle(
    color: Color(0xff6a9955),
    fontStyle: FontStyle.italic,
  ),
  'literal': const TextStyle(color: Color(0xffdcdcaa)),
  'variable': const TextStyle(color: Color(0xff9cdcfe)),
  'type': const TextStyle(color: Color(0xff4ec9b0)),
  'function': const TextStyle(color: Color(0xffdcdcaa)),
};

const List<String> sqlKeywords = [
  'SELECT',
  'FROM',
  'WHERE',
  'INSERT',
  'INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE',
  'CREATE',
  'TABLE',
  'DROP',
  'ALTER',
  'ADD',
  'COLUMN',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'OUTER',
  'ON',
  'GROUP',
  'BY',
  'ORDER',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'AND',
  'OR',
  'NOT',
  'NULL',
  'IS',
  'IN',
  'BETWEEN',
  'LIKE',
  'AS',
  'DISTINCT',
  'COUNT',
  'SUM',
  'AVG',
  'MAX',
  'MIN',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'CAST',
  'UNION',
  'ALL',
  'EXISTS',
  'ANY',
  'SOME',
  'DEFAULT',
  'UNIQUE',
  'INDEX',
  'VIEW',
  'TRIGGER',
  'PROCEDURE',
  'FUNCTION',
  'DATABASE',
  'SCHEMA',
  'SHOW',
  'DESCRIBE',
  'EXPLAIN',
  'PRAGMA',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'TRANSACTION',
  'GRANT',
  'REVOKE',
  'INT',
  'VARCHAR',
  'TEXT',
  'BOOLEAN',
  'DATE',
  'TIME',
  'TIMESTAMP',
  'FLOAT',
  'DOUBLE',
  'DECIMAL',
  'NUMERIC',
  'BLOB',
  'JSON',
  'UUID',
  'SERIAL',
  'BIGINT',
];
