// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/connections/domain/connection_config.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6562054069552780736),
      name: 'ConnectionConfig',
      lastPropertyId: const obx_int.IdUid(10, 4012404646491824754),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 876128107854044138),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8743531618365822453),
            name: 'uuid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 1726581896666547881)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2165554994633482501),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1689394513020186367),
            name: 'host',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7004812818342113170),
            name: 'port',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 811717173814351806),
            name: 'database',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4172751989873777978),
            name: 'username',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2811822112099767618),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5766665812015982841),
            name: 'filePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4012404646491824754),
            name: 'dbTypeIndex',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 6562054069552780736),
      lastIndexId: const obx_int.IdUid(1, 1726581896666547881),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ConnectionConfig: obx_int.EntityDefinition<ConnectionConfig>(
        model: _entities[0],
        toOneRelations: (ConnectionConfig object) => [],
        toManyRelations: (ConnectionConfig object) => {},
        getId: (ConnectionConfig object) => object.id,
        setId: (ConnectionConfig object, int id) {
          object.id = id;
        },
        objectToFB: (ConnectionConfig object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final nameOffset = fbb.writeString(object.name);
          final hostOffset = fbb.writeString(object.host);
          final databaseOffset = fbb.writeString(object.database);
          final usernameOffset = fbb.writeString(object.username);
          final passwordOffset = object.password == null
              ? null
              : fbb.writeString(object.password!);
          final filePathOffset = object.filePath == null
              ? null
              : fbb.writeString(object.filePath!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, hostOffset);
          fbb.addInt64(4, object.port);
          fbb.addOffset(5, databaseOffset);
          fbb.addOffset(6, usernameOffset);
          fbb.addOffset(7, passwordOffset);
          fbb.addOffset(8, filePathOffset);
          fbb.addInt64(9, object.dbTypeIndex);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uuidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final dbTypeIndexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final hostParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final portParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final databaseParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final usernameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final filePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final object = ConnectionConfig(
              id: idParam,
              uuid: uuidParam,
              name: nameParam,
              dbTypeIndex: dbTypeIndexParam,
              host: hostParam,
              port: portParam,
              database: databaseParam,
              username: usernameParam,
              password: passwordParam,
              filePath: filePathParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ConnectionConfig] entity fields to define ObjectBox queries.
class ConnectionConfig_ {
  /// see [ConnectionConfig.id]
  static final id =
      obx.QueryIntegerProperty<ConnectionConfig>(_entities[0].properties[0]);

  /// see [ConnectionConfig.uuid]
  static final uuid =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[1]);

  /// see [ConnectionConfig.name]
  static final name =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[2]);

  /// see [ConnectionConfig.host]
  static final host =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[3]);

  /// see [ConnectionConfig.port]
  static final port =
      obx.QueryIntegerProperty<ConnectionConfig>(_entities[0].properties[4]);

  /// see [ConnectionConfig.database]
  static final database =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[5]);

  /// see [ConnectionConfig.username]
  static final username =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[6]);

  /// see [ConnectionConfig.password]
  static final password =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[7]);

  /// see [ConnectionConfig.filePath]
  static final filePath =
      obx.QueryStringProperty<ConnectionConfig>(_entities[0].properties[8]);

  /// see [ConnectionConfig.dbTypeIndex]
  static final dbTypeIndex =
      obx.QueryIntegerProperty<ConnectionConfig>(_entities[0].properties[9]);
}
